title: Noah LaFerriere
baseURL: /
params:
  description: Noahs web porfolio
  layout_style: overflow
  palette: violet
  header:
    title: Noah LaFerriere
    tagline: Software Engineer
    profile_img: images/IMG_5182(1).jpeg
    profile_img_alt: Noah's Profile Pic
    background: dark
    has_nav: true
    nav_links:
      - label: Home
        url: /
        style: link
      - label: Work Experience
        url: /blog/
        style: link
      - label: My Projects
        url: /portfolio/
        style: link
      - label: Download My Resume
        url: /images/Noah_LaFerriere_Resume.pdf
        style: link
      - label: Contact
        url: /contact/
        style: link
        no_follow: true
    has_social: true
    social_links:
      - label: GitHub
        url: 'https://github.com/noah710'
        style: icon
        icon_class: fa-github
        new_window: true
      - label: LinkedIn
        url: 'https://www.linkedin.com/in/noah-laferriere-4880091ab/'
        style: icon
        icon_class: fa-linkedin
        new_window: true
  footer:
    content: All rights and lefts reserved.
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
